include: package:workiva_analysis_options/v1.recommended.yaml

analyzer:
  errors:
    must_call_super: error
    unused_import: warning
    duplicate_import: warning
    comment_references: info
linter:
  rules:
    prefer_if_elements_to_conditional_expressions: false
    overridden_fields: false
    type_annotate_public_apis: false
